export const DELETE_ITEM = 'DELETE_ITEM'; 
export const INCREMENT_ITEM = 'INCREMENT_ITEM'; 
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_SINGLE_ITEM_TO_CART = 'ADD_SINGLE_ITEM_TO_CART';
export const ADD_PAYMENT_DETAILS = 'ADD_PAYMENT_DETAILS';